# Operator code lives in chorus and is distributed to hosts as a content-addressed source bundle
# (definitions/build_bundles.py); ember executes it via ember/runner.py, sha-verified before exec.
# There are no code mirrors — changes happen here.
"""Category-theoretic core for deterministic operators — the content-context-operator
triple as an algebra.

An operator is a morphism f: content → context (an arrow). The triple
[[content-context-operator-triple]] is then just: a morphism and its two endpoints, so
knowing any 2 determines the 3rd:

  • content + operator → context   apply    (compute the result)
  • operator + context → content   preimage (solve / invert the arrow)
  • content + context → operator   infer    (which arrow maps these? — learn the operator)

`infer` is the developmental win: instead of hard-coding "multiply", the system learns
the operator from (content, context) examples by the gate/Occam rule — the simplest
morphism consistent with every example. That is the same "extract the law from data"
pattern as SINDy for dynamics, applied to operators.

This module's own algebra is four generators plus an identity, with `subtract`, `divide` and
`power` composed from them: subtract = add∘(id, negate); divide = multiply∘(id, invert);
power = fold multiply. That composition is real, executable and scoped to this module's eight
names (`ALGEBRA`) — it is not a claim about `arithmetic.py`'s own operator set.
`arithmetic.TRANSFORMS` dispatches through `_BY_SYMBOL` and never imports this module; `lcm`,
`floordiv`, `modulo`, `is_prime`, `factorize`, `sqrt`, `factorial` and `gcd` have no
compositional expression here. `infer` (`arithmetic.learn_operator`) is the only bridge between
the two.

Scope: this is the useful subset — the triple algebra plus composition. The full categorical
layer (category theory as an operator on itself — functors, natural transformations, the algebra
acting on its own arrows) is out of scope; this module stays concrete: numbers, arrows, and
'any 2 predict the 3rd'.
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import reduce
from typing import Callable, Dict, List, Optional, Sequence, Tuple


@dataclass(frozen=True)
class Morphism:
    """An arrow content → context. `cost` = # of generator applications (Occam weight);
    `solve` (optional) recovers a missing operand from the result + the known operands —
    this is the arrow's inverse, giving `preimage`."""
    name: str
    arity: int
    fn: Callable                                   # forward: *content -> context
    cost: int = 1
    solve: Optional[Callable] = None               # (result, known:list, missing_index) -> operand


# ── Generators — the whole algebra is generated by these four (+ identity) ────
_GEN: Dict[str, Morphism] = {
    "identity": Morphism("identity", 1, lambda a: a, 0, solve=lambda r, k, i: r),
    "add":      Morphism("add", 2, lambda a, b: a + b, 1,
                         solve=lambda r, k, i: r - k[1 - i]),
    "negate":   Morphism("negate", 1, lambda a: -a, 1, solve=lambda r, k, i: -r),
    "multiply": Morphism("multiply", 2, lambda a, b: a * b, 1,
                         solve=lambda r, k, i: r / k[1 - i]),
    "invert":   Morphism("invert", 1, lambda a: 1 / a, 1, solve=lambda r, k, i: 1 / r),
}


# ── Composition — derived operators, expressed in the generators ──────────────
def _compose_binary(name: str, base: str, post_second: str, cost: int) -> Morphism:
    """A binary op that applies `base` to (a, g(b)) where g is a unary generator —
    the shape of subtract (add∘negate) and divide (multiply∘invert)."""
    g = _GEN[post_second]; b = _GEN[base]
    return Morphism(
        name, 2, lambda x, y, _b=b, _g=g: _b.fn(x, _g.fn(y)), cost,
        # invert: know x,? or ?,y. missing 'y': y = g⁻¹(base⁻¹(r, x)); missing 'x': x = base⁻¹(r, g(y))
        solve=lambda r, k, i, _b=b, _g=g: (
            _g.solve(_b.solve(r, [k[0], None], 1), [None], 0) if i == 1
            else _b.solve(r, [None, _g.fn(k[1])], 0)
        ),
    )


DERIVED: Dict[str, Morphism] = {
    "subtract": _compose_binary("subtract", "add", "negate", 2),
    "divide":   _compose_binary("divide", "multiply", "invert", 2),
}


def _power() -> Morphism:
    # power(a, n) = fold multiply over n copies of a — a composition, not a new primitive.
    return Morphism("power", 2, lambda a, n: reduce(lambda x, _: _GEN["multiply"].fn(x, a),
                                                    range(int(n) - 1), a) if int(n) >= 1 else 1,
                    cost=3)


DERIVED["power"] = _power()

# The full addressable algebra: generators + derived — eight names. `gcd`, `factorize`,
# `is_prime` and `factorial` are outside this algebra — they are `math.gcd`, `math.factorial`
# and hand-written loops in `arithmetic.py`, not expressed over these generators — so `infer`
# can never name them, which is why the candidate filter below rejects anything not in `ALGEBRA`.
ALGEBRA: Dict[str, Morphism] = {**_GEN, **DERIVED}


# ── The triple: any 2 determine the 3rd ──────────────────────────────────────
def apply(operator: str, *content):
    """content + operator → context."""
    return _lookup(operator).fn(*content)


def preimage(operator: str, context, known: Sequence, missing_index: int):
    """operator + context → content: recover the operand at `missing_index` given the
    others (`known`, with None at the missing slot) and the result. Uses the arrow's
    inverse (`solve`)."""
    m = _lookup(operator)
    if m.solve is None:
        raise ValueError(f"operator '{operator}' is not invertible")
    return m.solve(context, list(known), missing_index)


# Candidate morphisms `infer` searches, cheapest first (Occam) — includes a couple of
# integer-only arrows so induction can find them from examples.
def _int_candidates() -> List[Morphism]:
    """Candidates `infer` may name.

    Every candidate must be executable by `apply`: a name that is not in `ALGEBRA` cannot be
    applied, so an inferred operator that cannot run would be worse than an honest `None`. The
    filter below is the invariant, not a list to keep in sync by hand.

    Arity-1 candidates are drawn from `ALGEBRA` itself (`identity`, `negate`, `invert`), so a
    unary example can be matched and every candidate stays executable by construction."""
    # `ALGEBRA` (`_GEN | DERIVED`) is identity, add, negate, multiply, invert, subtract, divide
    # and power. The filter below drops any candidate name not in `ALGEBRA` — "unexecutable →
    # never nameable" is the invariant. If an operator like `modulo` should be nameable, it
    # belongs in the algebra itself, not in a separate candidate list the algebra would veto.
    #
    # `negate` and `invert` are generators, in `_GEN` — `DERIVED` holds only
    # {subtract, divide, power}.
    unary = [m for m in (_GEN.get("identity"), _GEN.get("negate"), _GEN.get("invert"))
             if m is not None and m.arity == 1]
    cands = [_GEN["add"], _GEN["multiply"], DERIVED["subtract"], DERIVED["divide"],
             DERIVED["power"], *unary]
    seen, out = set(), []
    for m in cands:
        if m.name in seen or m.name not in ALGEBRA:   # unexecutable -> never nameable
            continue
        seen.add(m.name); out.append(m)
    return sorted(out, key=lambda m: m.cost)


def infer(examples: Sequence[Tuple[Sequence, object]], *, tol: float = 1e-9) -> Optional[str]:
    """content + context → operator: the simplest morphism reproducing every example
    exactly (the gate/Occam rule). `examples` = [(content_tuple, context), ...].
    Returns the operator name, or None if no candidate fits — an honest 'I can't name
    the transform', never a guess."""
    if not examples:
        return None
    arity = len(examples[0][0])
    fits: List[Morphism] = []
    for m in _int_candidates():
        if m.arity != arity:
            continue
        ok = True
        for content, context in examples:
            try:
                got = m.fn(*content)
            # `power`'s fold does `int(n)`, so a non-finite example like ((2, inf), 4) raises an
            # OverflowError; caught here alongside the other reasons a candidate can fail to fit.
            except (ZeroDivisionError, ValueError, TypeError, OverflowError):
                ok = False; break
            if isinstance(got, float) or isinstance(context, float):
                if abs(got - context) > tol:
                    ok = False; break
            elif got != context:
                ok = False; break
        if ok:
            fits.append(m)
    # Ambiguity is not an answer: a unique cheapest fit is an answer, a tie is a request for
    # another example. Returning the first fit at a shared cost would depend on list order, not
    # on Occam's razor or anything meaningful — `infer([(2,2)->4])`, for instance, fits both
    # `multiply` and `power` at the same cost.
    if not fits:
        return None
    best = fits[0].cost
    winners = [m.name for m in fits if m.cost == best]
    return winners[0] if len(winners) == 1 else None


def complete_triple(*, content=None, operator=None, context=None,
                    known=None, missing_index=None, examples=None):
    """Fill the missing corner of the triple from the other two.
      • content + operator  → {'context': ...}
      • operator + context  → {'content': ...}   (needs `known` + `missing_index`)
      • examples (content+context pairs) → {'operator': name}
    """
    if content is not None and operator is not None:
        return {"context": apply(operator, *content)}
    if operator is not None and context is not None and known is not None:
        return {"content": preimage(operator, context, known, missing_index)}
    if examples is not None:
        return {"operator": infer(examples)}
    raise ValueError("need exactly two of {content, operator, context/examples}")


def _lookup(name: str) -> Morphism:
    if name in ALGEBRA:
        return ALGEBRA[name]
    # allow the op.math.* ids used by the arithmetic domain
    short = name.split(".")[-1]
    if short in ALGEBRA:
        return ALGEBRA[short]
    raise KeyError(f"unknown morphism '{name}'")
