// crystal/__tests__/crystalModel.test.ts
//
// The crystal contract pinned (Operator Architecture §12): structure ships, state grows;
// facets conduct, tektons condense, organons discharge; the prism junction is one subset
// check. Mirrors agience-crystal/src/crystal/tests/test_crystal_model.py, plus
// cross-language byte-parity fixtures generated by the Python reference implementation.
import { describe, it, expect } from 'vitest';

import {
  CRYSTAL_CONTENT_TYPE,
  activatesOn,
  canonicalJson,
  crystalArtifact,
  crystalSha,
  requiredCapabilities,
  validate,
  verify,
  type Crystal,
} from '../crystalModel';

function _crystal(overrides: Partial<Crystal> = {}): Crystal {
  return {
    name: 'crystal.lexicon',
    facets: [
      { name: 'chat', direction: 'both' },
      { name: 'feed', direction: 'in' },
    ],
    tektons: [{ name: 'sage', domain: 'knowledge' }],
    organons: [
      { name: 'op.respond', requires: ['compute.local', 'store.read'] },
      { name: 'op.describe', requires: ['store.read'] },
    ],
    lattice_seed: { collections: ['stage.0.lexicon'] },
    created_by: 'person-1',
    ...overrides,
  };
}

const asRec = (c: Crystal) => c as unknown as Record<string, unknown>;

describe('crystal/crystalModel — validate', () => {
  it('valid crystal validates clean', () => {
    expect(validate(asRec(_crystal()))).toEqual([]);
  });

  it('sealed crystal refused (no facets = sealed glass)', () => {
    const problems = validate(asRec(_crystal({ facets: [] })));
    expect(problems.some((p) => p.includes('at least one facet'))).toBe(true);
  });

  it('no tekton refused', () => {
    const problems = validate(asRec(_crystal({ tektons: [] })));
    expect(problems.some((p) => p.includes('tektons'))).toBe(true);
  });

  it('bad facet direction refused', () => {
    const bad = _crystal({ facets: [{ name: 'x', direction: 'sideways' as never }] });
    expect(validate(asRec(bad)).some((p) => p.includes('direction'))).toBe(true);
  });

  it('pure-conduit crystal allowed (organons may be empty)', () => {
    expect(validate(asRec(_crystal({ organons: [] })))).toEqual([]);
  });
});

describe('crystal/crystalModel — the prism junction', () => {
  it('requiredCapabilities is the union, sorted', () => {
    expect(requiredCapabilities(_crystal())).toEqual(['compute.local', 'store.read']);
  });

  it('activatesOn is one subset check', () => {
    const c = _crystal();
    expect(activatesOn(c, ['compute.local', 'store.read', 'net.get'])).toBe(true); // superset → activates
    expect(activatesOn(c, ['store.read'])).toBe(false); // missing compute.local
    expect(activatesOn(_crystal({ organons: [] }), [])).toBe(true); // nothing required → any prism
  });
});

describe('crystal/crystalModel — sha & integrity', () => {
  it('sha ignores itself and is order-free', async () => {
    const c = _crystal();
    const s1 = await crystalSha(asRec(c));
    // same fields, different insert order
    const reversed: Record<string, unknown> = {};
    for (const k of Object.keys(asRec(_crystal())).reverse()) reversed[k] = asRec(_crystal())[k];
    expect(await crystalSha(reversed)).toBe(s1);
    // the sha field never hashes itself
    const c3 = asRec(_crystal());
    c3.sha256 = 'deadbeef';
    expect(await crystalSha(c3)).toBe(s1);
  });

  it('artifact roundtrip verifies clean; tampering is REFUSED', async () => {
    const art = await crystalArtifact(_crystal());
    expect(art.content_type).toBe(CRYSTAL_CONTENT_TYPE);
    const body = await verify(art); // clean roundtrip
    expect(body.sha256).toBe(await crystalSha(asRec(body)));
    // tamper with the structure → refused
    const tampered = JSON.parse(art.content);
    tampered.organons.push({ name: 'op.evil', requires: ['net.request'] });
    const artBad = { ...art, content: JSON.stringify(tampered) };
    await expect(verify(artBad)).rejects.toThrow(/integrity failure/);
  });

  it('invalid crystal cannot become an artifact', async () => {
    await expect(crystalArtifact(_crystal({ facets: [] }))).rejects.toThrow(/invalid crystal/);
  });
});

describe('crystal/crystalModel — canonicalJson byte-parity with Python', () => {
  // Every canonicaliser (prism-py, prism-c, prism-js, this SDK) targets RFC 8785 / JCS: raw UTF-8,
  // no \uXXXX escaping of non-ASCII. Fixture derived from the Python reference implementation:
  //   from prism.crystal_model import canonical_json
  //   fx = {'z': 'café ' + '😀', 'a': ['x', True, None, 7],
  //         'tab': 'a\tb"c\\d', 'nested': {'k2': [], 'k1': {}}}
  //   canonical_json(fx)  →  the string below (86 bytes)
  //   sha256(canonical_json(fx)) → bbd459992b905531e0ccd1c57d15fde9c1e1c8a8e8f4ec021630c59d9d5785b6
  it('escapes, sorts, and separates exactly like json.dumps(sort_keys=True, separators=(",",":"))', () => {
    const fx = {
      z: 'café 😀',
      a: ['x', true, null, 7],
      tab: 'a\tb"c\\d',
      nested: { k2: [], k1: {} },
    };
    expect(canonicalJson(fx)).toBe(
      '{"a":["x",true,null,7],"nested":{"k1":{},"k2":[]},"tab":"a\\tb\\"c\\\\d","z":"café 😀"}',
    );
  });

  it('canonical output keeps non-ASCII raw — it is not escaped to ASCII', () => {
    // RFC 8785 requires raw UTF-8 output, so the canonical string is not its own byte sequence —
    // which is why `sha256Hex` runs it through TextEncoder rather than reading charCodeAt.
    const out = canonicalJson({ k: 'café 0' });
    expect(out).toContain('é');
    expect(out).not.toContain('\\u00e9');   // the escaped form must be absent
    expect(new TextEncoder().encode(out).length).toBeGreaterThan(out.length);
  });

  it('undefined-valued properties are skipped (they do not exist in a Python dict)', () => {
    expect(canonicalJson({ a: 1, b: undefined })).toBe('{"a":1}');
  });
});
